#!/usr/bin/env node
/**
 * npm run setup - resolve every role to a model slug the router actually serves.
 *
 *   npm run setup                        fetch the live model list
 *   npm run setup -- --from-file <path>  use a saved /models response
 *   npm run setup -- --offline           write offline stubs (mock runs only)
 *   npm run setup -- --base-url <url>    point at a different router
 *
 * This runs before anything else because constraint C7 says no model id is ever
 * typed from memory. If the fetch fails, setup says so and exits non-zero. It
 * does not fall back to a guess, because a guessed slug is a 404 you pay for
 * later instead of an error you see now.
 */
import fs from 'node:fs';
import yaml from 'js-yaml';
import 'dotenv/config';

import { FILES, routerBaseUrl } from '../core/project.ts';
import { fetchCatalog, mockCatalog, normalizeCatalog, saveCatalog } from '../core/catalog.ts';
import type { Catalog } from '../core/catalog.ts';
import { PreferencesFile, resolveAll } from '../core/routing.ts';
import { AosError, isAosError } from '../core/errors.ts';

interface Args {
  fromFile?: string;
  offline: boolean;
  baseUrl: string;
}

function parseArgs(argv: string[]): Args {
  const args: Args = { offline: false, baseUrl: routerBaseUrl() };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--offline') args.offline = true;
    else if (a === '--from-file') args.fromFile = argv[++i];
    else if (a === '--base-url') args.baseUrl = argv[++i] ?? args.baseUrl;
    else if (a === '--help' || a === '-h') {
      console.log('usage: npm run setup -- [--from-file <path>] [--offline] [--base-url <url>]');
      process.exit(0);
    } else throw new AosError('CATALOG', `unknown argument: ${a}`);
  }
  return args;
}

async function obtainCatalog(args: Args): Promise<Catalog> {
  if (args.offline) {
    console.log('mode: offline stubs (no network, mock transport only)');
    return mockCatalog(args.baseUrl, new Date().toISOString());
  }
  if (args.fromFile) {
    console.log(`mode: model list from file ${args.fromFile}`);
    return normalizeCatalog(
      JSON.parse(fs.readFileSync(args.fromFile, 'utf-8')),
      args.baseUrl,
      new Date().toISOString(),
      'file',
    );
  }
  console.log(`mode: live fetch from ${args.baseUrl}/models`);
  return fetchCatalog(args.baseUrl);
}

function table(rows: string[][], head: string[]): string {
  const all = [head, ...rows];
  const w = head.map((_, i) => Math.max(...all.map((r) => r[i]!.length)));
  return all.map((r) => r.map((c, i) => c.padEnd(w[i]!)).join('  ').trimEnd()).join('\n');
}

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));
  const catalog = await obtainCatalog(args);
  console.log(`catalog: ${catalog.models.length} models, source=${catalog.source}`);
  saveCatalog(FILES.catalog, catalog);

  const prefs = PreferencesFile.parse(yaml.load(fs.readFileSync(FILES.routing, 'utf-8')));
  const lock = resolveAll(catalog, prefs);

  fs.writeFileSync(
    FILES.routingLock,
    [
      '# GENERATED by `npm run setup`. Do not hand-edit.',
      '#',
      '# Every slug here came from the router model list fetched at the timestamp',
      '# below. Regenerate rather than patch: a slug edited by hand is exactly the',
      `# failure constraint C7 exists to prevent.`,
      '#',
      `# Source: ${catalog.source}   Fetched: ${catalog.fetchedAt}`,
      '',
      yaml.dump(lock, { lineWidth: 100 }),
    ].join('\n'),
    'utf-8',
  );

  const rows = Object.entries(lock.roles).map(([role, r]) => [
    role,
    r.model,
    r.fallback,
    r.parallel.length > 0 ? r.parallel.join(', ') : '',
  ]);
  console.log('');
  console.log(table(rows, ['ROLE', 'PRIMARY', 'FALLBACK', 'PARALLEL']));
  console.log('');
  console.log(`wrote ${FILES.catalog}`);
  console.log(`wrote ${FILES.routingLock}`);

  if (catalog.source === 'mock') {
    console.log('');
    console.log('These are offline stubs, not models. Runs will use the mock transport and');
    console.log('report simulated costs. Re-run without --offline once the router is reachable.');
  }
}

main().catch((err: unknown) => {
  if (isAosError(err)) {
    console.error(`\nsetup failed [${err.code}]: ${err.message}`);
    const hint = err.detail.hint;
    if (typeof hint === 'string') console.error(`\n  ${hint}`);
    if (err.code === 'CATALOG') {
      console.error('\n  If egress is restricted, fetch the list from a machine that can reach');
      console.error('  the router, then:   npm run setup -- --from-file <models.json>');
      console.error('  To exercise the pipeline with no network at all:');
      console.error('                      npm run setup -- --offline');
      console.error('\n  Nothing was written. No role has a model slug, so the next run will');
      console.error('  refuse to start. That is deliberate: an unresolved role fails loudly at');
      console.error('  startup, a guessed model slug fails quietly after you have already paid.');
    }
  } else {
    console.error(`\nsetup failed: ${err instanceof Error ? err.stack : String(err)}`);
  }
  process.exit(1);
});
