/**
 * The offline stub responder.
 *
 * This is NOT a model and does not simulate one. It returns the minimum
 * schema-valid output for each role so the state machine, the budget meter, the
 * sandbox, the delivery gate and the event log can all be exercised end to end
 * on a machine with no API key and no egress.
 *
 * Everything it produces says so, in the artifact itself and in cost.json. The
 * point of a demo is to prove the machine works, and a demo that quietly passes
 * off canned text as model output proves nothing at all.
 */
import type { TransportRequest } from './transport.ts';

function stubPage(idea: string): string {
  const safe = idea.replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c]!);
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>AOS offline stub artifact</title>
<style>
  :root { color-scheme: light dark; }
  body { font: 16px/1.6 system-ui, sans-serif; max-width: 42rem; margin: 3rem auto; padding: 0 1rem; }
  .banner { border: 2px solid #b45309; background: #fef3c7; color: #7c2d12; padding: 1rem; border-radius: 8px; }
  code { background: rgba(127,127,127,.18); padding: .1rem .3rem; border-radius: 3px; }
  output { font-size: 2rem; font-weight: 600; display: block; margin-top: 1rem; }
  label { display: block; margin-top: 1rem; }
  input { font: inherit; padding: .4rem; width: 8rem; }
</style>
</head>
<body>
  <div class="banner">
    <strong>This artifact was produced by the AOS offline stub, not by a model.</strong>
    <p>The run used <code>--offline</code>, so no model was called and no money was
    spent. It exists to prove the pipeline writes a real, runnable file through the
    sandbox. Run <code>npm run setup</code> against a reachable router and re-run
    without <code>--offline</code> to get an artifact a model actually wrote.</p>
  </div>

  <h1>Work order</h1>
  <p>The idea passed to this run was:</p>
  <blockquote>${safe}</blockquote>

  <h2>Proof this file runs</h2>
  <p>The field below is wired to real JavaScript, so opening this file in a
  browser demonstrates that the artifact is executable rather than a description
  of one.</p>
  <label>Type a number: <input id="n" type="number" value="8"></label>
  <output id="out">waiting</output>

<script>
  const n = document.getElementById('n');
  const out = document.getElementById('out');
  function render() {
    const v = Number.parseFloat(n.value);
    out.textContent = Number.isFinite(v) ? v + ' squared is ' + (v * v) : 'not a number';
  }
  n.addEventListener('input', render);
  render();
</script>
</body>
</html>
`;
}

/** Minimum schema-valid output per role. Keyed on the role, not on the prompt. */
export function offlineResponder(idea: string): (req: TransportRequest) => string {
  let museCalls = 0;

  return (req: TransportRequest): string => {
    switch (req.role) {
      case 'MUSE': {
        const angles = ['minimal', 'differently shaped', 'questioning the request'];
        const angle = angles[museCalls++ % angles.length]!;
        return JSON.stringify({
          title: `Offline stub option: the ${angle} approach`,
          sketch: `A placeholder option produced without calling a model. It stands in for the ${angle} take on: ${idea}`,
          whyNot: 'It was not generated by a model, so it carries no actual insight.',
        });
      }

      case 'ATLAS':
        return JSON.stringify({
          chosenOption: 'Offline stub option: the minimal approach',
          rationale: 'Chosen by the offline stub because it is first, not because it is best.',
          tier: 'GREEN',
          reversible: true,
          tasks: [
            {
              id: 'T1',
              title: 'Produce a runnable artifact for the stated idea',
              assignee: 'FORGE',
              acceptance: 'A file exists under artifacts/ that opens in a browser and executes.',
            },
          ],
          decisions: [
            {
              title: 'Run the pipeline against offline stubs',
              chosen: 'Exercise every stage without calling a model',
              alternatives: ['Wait for router access', 'Skip the end-to-end run'],
              assumptions: ['The machinery can be validated separately from model quality'],
              falsifier: 'A live run fails at a stage the offline run passed, meaning the stub hid a real defect.',
              reviewInDays: 7,
            },
          ],
        });

      case 'FORGE':
        return JSON.stringify({
          files: [{ path: 'index.html', kind: 'code', runnable: true, contents: stubPage(idea) }],
          notes: 'Written by the offline stub. Contains no model output.',
        });

      case 'ECHO':
        return JSON.stringify({
          objections: [
            {
              claim: 'The artifact was produced by a stub, so it does not implement the requested idea',
              severity: 'S2',
              falsifier: 'Open the artifact and check whether it does what the idea asked for. It does not.',
            },
          ],
        });

      case 'SENTINEL':
        return JSON.stringify({
          defects: [],
          testsRun: [
            'Confirmed the artifact file exists inside the run sandbox',
            'Confirmed it is a complete HTML document with an executable script block',
          ],
        });

      case 'HERALD':
        return JSON.stringify({
          headline: 'Offline stub run completed end to end',
          whatShipped:
            'Every pipeline stage ran and produced a runnable artifact, a cost report and a full event log, without calling a model.',
          howToRun: 'Open artifacts/index.html in a browser.',
          risks: [
            'No model was called, so nothing here reflects model quality.',
            'The artifact does not implement the requested idea.',
          ],
          unverifiedClaims: [],
        });

      default:
        return JSON.stringify({ error: `the offline stub has no canned reply for role ${req.role}` });
    }
  };
}
