/**
 * Turning a live model list into role assignments.
 *
 * The build prompt's routing table (a divergent model for ideas, a structured
 * one for planning and building, two providers for the critic) is a hypothesis,
 * not a ranking, so it is encoded as *preferences* — a provider order and a
 * price tier — rather than as slugs. `npm run setup` resolves those preferences
 * against whatever the router is actually serving today.
 *
 * Two files, on purpose:
 *
 *   config/routing.yaml       the hypothesis. Hand-authored, committed, small
 *                             enough to argue about in a review.
 *   config/routing.lock.yaml  the resolved slugs. Machine-written, gitignored,
 *                             regenerated by setup. Never hand-edited, which is
 *                             constraint C7 made structural rather than polite.
 *
 * The scoreboard (feature 6.2) is what eventually replaces the hypothesis with
 * measurement. Until then, at least the guess cannot go stale silently.
 */
import { z } from 'zod';
import { AosError } from './errors.ts';
import { PLACEHOLDER } from './catalog.ts';
import type { Catalog, CatalogEntry } from './catalog.ts';

/** The hypothesis. One entry per role in config/routing.yaml. */
export const RolePreference = z.object({
  /** Provider slugs in order of preference, e.g. ["google", "openai"]. */
  prefer: z.array(z.string()).min(1),
  tier: z.enum(['cheap', 'mid', 'top']),
  minContext: z.number().int().positive().default(32_000),
  /** Run a second model from a different provider in parallel (ECHO does). */
  secondOpinion: z.boolean().default(false),
});
export type RolePreference = z.infer<typeof RolePreference>;

export const PreferencesFile = z.object({
  version: z.literal(1),
  roles: z.record(z.string(), RolePreference),
});
export type PreferencesFile = z.infer<typeof PreferencesFile>;

/** The resolution. config/routing.lock.yaml, written by setup. */
export const RoleRouting = z.object({
  model: z.string(),
  fallback: z.string(),
  /** Extra models run in parallel for this role, e.g. ECHO's second critic. */
  parallel: z.array(z.string()).default([]),
});
export type RoleRouting = z.infer<typeof RoleRouting>;

export const RoutingLock = z.object({
  version: z.literal(1),
  catalog: z.object({ source: z.string(), fetchedAt: z.string(), baseUrl: z.string() }),
  roles: z.record(z.string(), RoleRouting),
});
export type RoutingLock = z.infer<typeof RoutingLock>;

/** Model families that are not chat completions and would fail mid-run. */
const NOT_CHAT = /(embed|embedding|whisper|tts|moderation|rerank|image|dall-e|sora|imagen|guard)/i;

/**
 * Output-heavy workload, so completion price dominates the blend. This is a
 * ranking key, not a cost estimate; actual cost comes from real usage.
 */
function blendedPrice(m: CatalogEntry): number {
  return m.promptUsdPerToken + 3 * m.completionUsdPerToken;
}

export function candidatesFor(catalog: Catalog, provider: string, minContext: number): CatalogEntry[] {
  return catalog.models
    .filter((m) => m.provider === provider)
    .filter((m) => !NOT_CHAT.test(m.id))
    .filter((m) => (m.contextLength ?? 0) >= minContext)
    // Zero-priced entries are usually rate-limited or preview aliases; a run
    // that silently lands on one reports a cost of $0 and teaches nothing.
    .filter((m) => blendedPrice(m) > 0)
    .sort((a, b) => blendedPrice(a) - blendedPrice(b));
}

function byTier(sorted: CatalogEntry[], tier: 'cheap' | 'mid' | 'top'): CatalogEntry | undefined {
  if (sorted.length === 0) return undefined;
  if (tier === 'cheap') return sorted[0];
  if (tier === 'top') return sorted[sorted.length - 1];
  return sorted[Math.floor((sorted.length - 1) / 2)];
}

export interface Resolution {
  model: string;
  fallback: string;
  provider: string;
  fallbackProvider: string;
}

/**
 * Resolve one role. The fallback is deliberately drawn from a *different*
 * provider than the primary: a fallback that shares an outage with the primary
 * is not a fallback.
 */
export function resolveRole(catalog: Catalog, role: string, pref: RolePreference): Resolution {
  const chosen: Array<{ entry: CatalogEntry; provider: string }> = [];

  for (const provider of pref.prefer) {
    const entry = byTier(candidatesFor(catalog, provider, pref.minContext), pref.tier);
    if (entry) chosen.push({ entry, provider });
    if (chosen.length === 2) break;
  }

  if (chosen.length === 0) {
    throw new AosError(
      'MODEL_UNRESOLVED',
      `no model in the catalog satisfies role ${role} (providers: ${pref.prefer.join(', ')}, min context ${pref.minContext})`,
      { role, pref, catalogSource: catalog.source, catalogSize: catalog.models.length },
    );
  }

  const primary = chosen[0]!;
  const secondary = chosen[1] ?? primary;
  return {
    model: primary.entry.id,
    fallback: secondary.entry.id,
    provider: primary.provider,
    fallbackProvider: secondary.provider,
  };
}

export function resolveAll(catalog: Catalog, prefs: PreferencesFile): RoutingLock {
  const roles: Record<string, RoleRouting> = {};
  for (const [role, pref] of Object.entries(prefs.roles)) {
    const res = resolveRole(catalog, role, pref);
    roles[role] = {
      model: res.model,
      fallback: res.fallback,
      parallel: pref.secondOpinion ? [res.fallback] : [],
    };
  }
  return RoutingLock.parse({
    version: 1,
    catalog: { source: catalog.source, fetchedAt: catalog.fetchedAt, baseUrl: catalog.baseUrl },
    roles,
  });
}

/** Roles whose slugs setup has not resolved yet. An empty list means ready. */
export function unresolvedRoles(lock: RoutingLock): string[] {
  const bad = new Set<string>();
  for (const [role, r] of Object.entries(lock.roles)) {
    for (const slug of [r.model, r.fallback, ...r.parallel]) {
      if (slug.includes(PLACEHOLDER) || slug.trim().length === 0) bad.add(role);
    }
  }
  return [...bad];
}
